set(CMAKE_PROJECT_NAME "mpsym")
set(CMAKE_PROJECT_VERSION "0.1")
set(CMAKE_PROJECT_DESCRIPTION "MPSoC Symmetry Reduction")
set(CMAKE_PROJECT_HOMEPAGE_URL "https://github.com/Time0o/mpsym")
set(CMAKE_PROJECT_DOC_URL "https://time0o.github.io/mpsym/")
set(CMAKE_PROJECT_AUTHOR "Timo Nicolai")
set(CMAKE_PROJECT_COPYRIGHT "2020")
set(CMAKE_PROJECT_LICENSE "MIT")
